# DS 4400 Homework 1 - Code
## Ariv Ahuja
### January 2026

In [1]:
import pandas as pd
import numpy as np

## Problem 4.2: Random Matrices and Inverses

In [2]:
# Set random seed for reproducibility
np.random.seed(42)

print("="*80)
print("PROBLEM 4.2: Random Matrices and Inverses")
print("="*80)

for i in range(3):
    # Generate random 3x3 matrix with integers from -10 to 10
    M = np.random.randint(-10, 11, size=(3, 3))
    print(f"\nMatrix {i+1}:")
    print(M)
    
    # Compute determinant
    det = np.linalg.det(M)
    print(f"\nDeterminant: {det:.4f}")
    
    # Compute inverse if it exists
    if abs(det) > 1e-10:
        M_inv = np.linalg.inv(M)
        print(f"\nInverse:")
        print(M_inv)
        print(f"\nM @ M^(-1) (should be identity):")
        print(np.round(M @ M_inv, 10))
    else:
        print("\nMatrix is singular, no inverse exists.")
    
    print("\n" + "-"*40)

PROBLEM 4.2: Random Matrices and Inverses

Matrix 1:
[[-4  9  4]
 [ 0 -3 10]
 [-4  8  0]]

Determinant: -88.0000

Inverse:
[[ 0.90909091 -0.36363636 -1.15909091]
 [ 0.45454545 -0.18181818 -0.45454545]
 [ 0.13636364  0.04545455 -0.13636364]]

M @ M^(-1) (should be identity):
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]

----------------------------------------

Matrix 2:
[[ 0 10 -7]
 [-3 -8 10]
 [-9  1 -5]]

Determinant: -525.0000

Inverse:
[[-0.05714286 -0.08190476 -0.08380952]
 [ 0.2         0.12       -0.04      ]
 [ 0.14285714  0.17142857 -0.05714286]]

M @ M^(-1) (should be identity):
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

----------------------------------------

Matrix 3:
[[ -9  10 -10]
 [  1   1   6]
 [ -1   5   4]]

Determinant: 74.0000

Inverse:
[[-0.35135135 -1.21621622  0.94594595]
 [-0.13513514 -0.62162162  0.59459459]
 [ 0.08108108  0.47297297 -0.25675676]]

M @ M^(-1) (should be identity):
[[ 1. -0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]

---------------------------

## Problem 5: Average, Variance, and Correlation

In [4]:
# Load the data
df = pd.read_csv('kc_house_data.csv')
print(f"Dataset shape: {df.shape}")
print(f"\nColumn names: {list(df.columns)}")

Dataset shape: (21613, 21)

Column names: ['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15']


In [5]:
# Remove id, date, and zipcode columns as instructed
cols_to_remove = ['id', 'date', 'zipcode']
df_analysis = df.drop(columns=cols_to_remove)

# Get feature columns (excluding price which is the response)
features = [col for col in df_analysis.columns if col != 'price']
print(f"Features to analyze: {features}")

Features to analyze: ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'lat', 'long', 'sqft_living15', 'sqft_lot15']


### Part 1: Feature Statistics

In [6]:
# Compute statistics for each feature
stats = {}
for col in features:
    stats[col] = {
        'average': df_analysis[col].mean(),
        'min': df_analysis[col].min(),
        'max': df_analysis[col].max(),
        'variance': df_analysis[col].var()
    }

# Create and display statistics DataFrame
stats_df = pd.DataFrame(stats).T
stats_df.columns = ['Average', 'Min', 'Max', 'Variance']
print("Feature Statistics:")
print(stats_df.to_string())

Feature Statistics:
                    Average        Min           Max      Variance
bedrooms           3.370842     0.0000  3.300000e+01  8.650150e-01
bathrooms          2.114757     0.0000  8.000000e+00  5.931513e-01
sqft_living     2079.899736   290.0000  1.354000e+04  8.435337e+05
sqft_lot       15106.967566   520.0000  1.651359e+06  1.715659e+09
floors             1.494309     1.0000  3.500000e+00  2.915880e-01
waterfront         0.007542     0.0000  1.000000e+00  7.485226e-03
view               0.234303     0.0000  4.000000e+00  5.872426e-01
condition          3.409430     1.0000  5.000000e+00  4.234665e-01
grade              7.656873     1.0000  1.300000e+01  1.381703e+00
sqft_above      1788.390691   290.0000  9.410000e+03  6.857347e+05
sqft_basement    291.509045     0.0000  4.820000e+03  1.958727e+05
yr_built        1971.005136  1900.0000  2.015000e+03  8.627973e+02
yr_renovated      84.402258     0.0000  2.015000e+03  1.613462e+05
lat               47.560053    47.1559  4.

In [7]:
# Find lowest and highest average
avg_sorted = sorted(stats.items(), key=lambda x: x[1]['average'])
print(f"\nFeature with LOWEST average: {avg_sorted[0][0]} = {avg_sorted[0][1]['average']:.4f}")
print(f"Feature with HIGHEST average: {avg_sorted[-1][0]} = {avg_sorted[-1][1]['average']:.4f}")


Feature with LOWEST average: long = -122.2139
Feature with HIGHEST average: sqft_lot = 15106.9676


In [8]:
# Find lowest and highest variance
var_sorted = sorted(stats.items(), key=lambda x: x[1]['variance'])
print(f"\nFeature with LOWEST variance: {var_sorted[0][0]} = {var_sorted[0][1]['variance']:.4f}")
print(f"Feature with HIGHEST variance: {var_sorted[-1][0]} = {var_sorted[-1][1]['variance']:.4f}")


Feature with LOWEST variance: waterfront = 0.0075
Feature with HIGHEST variance: sqft_lot = 1715658774.1755


### Part 2: Correlation with Response (price)

In [9]:
# Compute correlation coefficient of each feature with price
correlations = {}
for col in features:
    correlations[col] = df_analysis[col].corr(df_analysis['price'])

# Create and display correlation DataFrame
corr_df = pd.DataFrame(list(correlations.items()), columns=['Feature', 'Correlation with Price'])
corr_df = corr_df.sort_values('Correlation with Price', ascending=False)
print("Correlation Coefficients with Price:")
print(corr_df.to_string(index=False))

Correlation Coefficients with Price:
      Feature  Correlation with Price
  sqft_living                0.702035
        grade                0.667434
   sqft_above                0.605567
sqft_living15                0.585379
    bathrooms                0.525138
         view                0.397293
sqft_basement                0.323816
     bedrooms                0.308350
          lat                0.307003
   waterfront                0.266369
       floors                0.256794
 yr_renovated                0.126434
     sqft_lot                0.089661
   sqft_lot15                0.082447
     yr_built                0.054012
    condition                0.036362
         long                0.021626


In [10]:
# Find positively correlated features
pos_corr = {k: v for k, v in correlations.items() if v > 0}
print(f"\nPositively correlated features ({len(pos_corr)} total):")
for feature in pos_corr.keys():
    print(f"  - {feature}")


Positively correlated features (17 total):
  - bedrooms
  - bathrooms
  - sqft_living
  - sqft_lot
  - floors
  - waterfront
  - view
  - condition
  - grade
  - sqft_above
  - sqft_basement
  - yr_built
  - yr_renovated
  - lat
  - long
  - sqft_living15
  - sqft_lot15


In [11]:
# Find feature with highest positive correlation
max_corr_feature = max(correlations.items(), key=lambda x: x[1])
print(f"\nFeature with HIGHEST positive correlation: {max_corr_feature[0]} = {max_corr_feature[1]:.6f}")


Feature with HIGHEST positive correlation: sqft_living = 0.702035


### Part 3: Negative Correlations

In [12]:
# Find negatively correlated features
neg_corr = {k: v for k, v in correlations.items() if v < 0}

if neg_corr:
    print(f"Features with NEGATIVE correlation ({len(neg_corr)} total):")
    for feature, corr in neg_corr.items():
        print(f"  - {feature}: {corr:.6f}")
else:
    print("No features have a negative correlation with price.")
    print("All 17 features are positively correlated with the response variable.")

No features have a negative correlation with price.
All 17 features are positively correlated with the response variable.
